version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_django
    container_name: {{ cookiecutter.project_slug }}_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - ./django:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.production/.postgres
      - ./.envs/.django
    environment:
      - VIRTUAL_HOST=api.{{ cookiecutter.domain_name.split(".")[0] }}.local
    networks:
      - nginxproxy_local_network
      - {{ cookiecutter.project_slug }}_local_network
    expose:
      - "8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_postgres
    container_name: {{ cookiecutter.project_slug }}_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    environment:
      - VIRTUAL_HOST=postgres.{{ cookiecutter.domain_name.split(".")[0] }}.local
    networks:
      - nginxproxy_local_network
      - {{ cookiecutter.project_slug }}_local_network
    expose:
      - "5432"

  redis:
    image: redis:5.0
    container_name: {{ cookiecutter.project_slug }}_local_redis
    networks:
      - {{ cookiecutter.project_slug }}_local_network

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_celeryworker
    container_name: {{ cookiecutter.project_slug }}_local_celeryworker
    expose: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_celerybeat
    container_name: {{ cookiecutter.project_slug }}_local_celerybeat
    expose: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_flower
    container_name: {{ cookiecutter.project_slug }}_local_flower
    environment:
      - VIRTUAL_HOST=flower.{{ cookiecutter.domain_name.split(".")[0] }}.local
    expose:
      - "5555"
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_node
    container_name: {{ cookiecutter.project_slug }}_local_node
    depends_on:
      - django
    volumes:
      - ./django:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev


networks:
  {{ cookiecutter.project_slug }}_local_network:
    name: {{ cookiecutter.project_slug }}_local_network
  nginxproxy_local_network:
    external: true
